apiVersion: v1
kind: Template
metadata:
  name: acme-app-build-and-deploy-template
objects:
- kind: Pipeline
  apiVersion: tekton.dev/v1beta1
  metadata:
    name: acme-app-build-and-deploy
  spec:
    workspaces:
      - name: workspace-acme   
    params:
    - name: target-namespace
      type: string
      default: "${DEFAULT_TARGET_NAMESPACE}"
      description: name of the deployment to be patched
    tasks:
      - name: fetch-repository
        taskRef:
          name: git-clone
          kind: ClusterTask        
        workspaces:
          - name: output
            workspace: workspace-acme
        params:
          - name: url
            value: https://github.com/eljeko/tekton-s2i-binary-deploy   
          - name: deleteExisting
            value: "true"
          - name: subdirectory
            value: ""        
      - name: build-app  
        taskRef:
          name: maven-build
        workspaces:
          - name: source
            workspace: workspace-acme 
        runAfter:
          - fetch-repository
      - name: deploy-app  
        taskRef:
          name: eap-binary-deploy
        params:
          - name: namespace
            value: "$(params.target-namespace)"
        workspaces:
          - name: source
            workspace: workspace-acme 
        runAfter:
          - build-app    
parameters:
- description: Prefix for the projects
  from: '[A-Z0-9]{8}'
  generate: expression
  name: DEFAULT_TARGET_NAMESPACE