apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: maven-build
spec:
  workspaces:
  - name: source
    description: The workspace where the source code will found
  steps:  
  - name: build
    image: maven:3.6.0-jdk-8-slim
    command:
      - /usr/bin/mvn
    args:
    - -f /workspace/source/acme-app/pom.xml 
    - clean 
    - package 
    - -Dappversion=1.0