apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: maven-build
spec:
  workspaces:
  - name: source
    description: The workspace where the source code will found
  steps:  
  - name: build
    image: maven:3.6.0-jdk-8-slim
    command: ["/bin/bash", "-c"]      
    args:
    - /usr/bin/mvn -f /workspace/source/acme-app/pom.xml clean package -Dappversion=1.2