apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: get-pods-namespace-task
spec:
  params:
    - name: namespace
      type: string
  steps:
    - name: get-pods
      image: quay.io/openshift/origin-cli:latest
      command: ["/bin/bash", "-c"]
      args:
        - |-
          oc get pods -n $(params.namespace) --token=